-- MySQL Script generated by MySQL Workbench
-- Thu Feb 14 19:13:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Components` (
  `idComponents` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `version` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idComponents`),
  UNIQUE INDEX `idComponents_UNIQUE` (`idComponents` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `idTest` INT NOT NULL AUTO_INCREMENT,
  `test_name` VARCHAR(255) NOT NULL,
  `test_type` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTest`),
  UNIQUE INDEX `idTest_UNIQUE` (`idTest` ASC) VISIBLE,
  UNIQUE INDEX `test_name_UNIQUE` (`test_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test_results` (
  `idTest_result` INT NOT NULL AUTO_INCREMENT,
  `case_name` VARCHAR(255) NULL,
  `result` VARCHAR(50) NULL,
  `reason` VARCHAR(4000) NULL,
  PRIMARY KEY (`idTest_result`),
  UNIQUE INDEX `idTest_result_UNIQUE` (`idTest_result` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Progon` (
  `idProgon` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  PRIMARY KEY (`idProgon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test_has_Progon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test_has_Progon` (
  `Test_idTest` INT NOT NULL,
  `Progon_idProgon` INT NOT NULL,
  PRIMARY KEY (`Test_idTest`, `Progon_idProgon`),
  INDEX `fk_Test_has_Progon_Progon1_idx` (`Progon_idProgon` ASC) VISIBLE,
  INDEX `fk_Test_has_Progon_Test_idx` (`Test_idTest` ASC) VISIBLE,
  CONSTRAINT `fk_Test_has_Progon_Test`
    FOREIGN KEY (`Test_idTest`)
    REFERENCES `mydb`.`Test` (`idTest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_has_Progon_Progon1`
    FOREIGN KEY (`Progon_idProgon`)
    REFERENCES `mydb`.`Progon` (`idProgon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progon_has_Components`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Progon_has_Components` (
  `Progon_idProgon` INT NOT NULL,
  `Components_idComponents` INT NOT NULL,
  PRIMARY KEY (`Progon_idProgon`, `Components_idComponents`),
  INDEX `fk_Progon_has_Components_Components1_idx` (`Components_idComponents` ASC) VISIBLE,
  INDEX `fk_Progon_has_Components_Progon1_idx` (`Progon_idProgon` ASC) VISIBLE,
  CONSTRAINT `fk_Progon_has_Components_Progon1`
    FOREIGN KEY (`Progon_idProgon`)
    REFERENCES `mydb`.`Progon` (`idProgon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Progon_has_Components_Components1`
    FOREIGN KEY (`Components_idComponents`)
    REFERENCES `mydb`.`Components` (`idComponents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progon_has_Test_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Progon_has_Test_results` (
  `Progon_idProgon` INT NOT NULL,
  `Test_results_idTest_result` INT NOT NULL,
  PRIMARY KEY (`Progon_idProgon`, `Test_results_idTest_result`),
  INDEX `fk_Progon_has_Test_results_Test_results1_idx` (`Test_results_idTest_result` ASC) VISIBLE,
  INDEX `fk_Progon_has_Test_results_Progon1_idx` (`Progon_idProgon` ASC) VISIBLE,
  CONSTRAINT `fk_Progon_has_Test_results_Progon1`
    FOREIGN KEY (`Progon_idProgon`)
    REFERENCES `mydb`.`Progon` (`idProgon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Progon_has_Test_results_Test_results1`
    FOREIGN KEY (`Test_results_idTest_result`)
    REFERENCES `mydb`.`Test_results` (`idTest_result`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
